language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
  - cp -R ./build ./client/
  - rm -R ./build
  - cd client
  - npm install
  - node server.js &
  - cd ..
  - npm run test